DROP TABLE USER IF EXISTS;
CREATE TABLE USER(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(36) NOT NULL
);
INSERT INTO USER VALUES(NULL, 'TEST', 'TEST');

DROP TABLE BLOG IF EXISTS;
CREATE TABLE BLOG(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(32767) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL
);
INSERT INTO BLOG VALUES(NULL, 'TITLE0', 'COTENT0', NOW());

DROP TABLE COMMENT IF EXISTS;
CREATE TABLE COMMENT(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	CONTENT VARCHAR(512) NOT NULL,
	USERNAME VARCHAR(255) NOT NULL,
	BLOG_ID BIGINT NOT NULL,
	DATE_COMMENTED TIMESTAMP NOT NULL
);
INSERT INTO COMMENT VALUES(NULL, 'FOO', 'XnnYygn', 1, NOW());

DROP TABLE TAG IF EXISTS;
CREATE TABLE TAG(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TEXT VARCHAR(255) NOT NULL
);
INSERT INTO TAG VALUES(NULL, 'FOO');

CREATE TABLE BLOG_TAGS(
    BLOG_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL,
    PRIMARY KEY(BLOG_ID, TAG_ID)
);