DROP TABLE BLOG IF EXISTS;
CREATE TABLE BLOG(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(32767) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL
);
INSERT INTO BLOG VALUES(NULL, 'TITLE0', 'COTENT0', NOW());