DROP TABLE USER IF EXISTS;
CREATE TABLE USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL
);

INSERT INTO USER(NAME) VALUES('XnnYygn');
INSERT INTO USER(NAME) VALUES('GSSxGSS');

DROP TABLE BLOG IF EXISTS;
CREATE TABLE BLOG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(32767) NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL,
    USER_ID BIGINT NOT NULL
);

INSERT INTO BLOG(TITLE, CONTENT, DATE_CREATED, USER_ID) VALUES('FIRST', 'HELLO, WORLD!', '2012-01-01 00:00:00', 1);
INSERT INTO BLOG(TITLE, CONTENT, DATE_CREATED, USER_ID) VALUES('SECOND', 'HELLO, WORLD!', '2012-01-01 00:00:00', 1)